# Shell
# set-option -g default-shell /opt/homebrew/bin/bash
set-option -g default-command "/opt/homebrew/bin/bash"

# Terminal
set -g mouse on
set -s escape-time 0
set-option -g focus-events on
set-option -g history-limit 30000
setw -g mode-keys vi

# Windows and Panes
bind-key % split-window -h -c "#{pane_current_path}"
bind-key '"' split-window -c "#{pane_current_path}"
bind-key c new-window -c "#{pane_current_path}"
set -g base-index 1
setw -g pane-base-index 1
set -g status-left-length 20

# Better Vim-style bindings for copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# Dark Theme
set-option -g status-style fg=white,bg=#000000
set-option -g status-left-style fg=brightcyan,bg=#000000
set-window-option -g window-status-current-style fg=brightblue

# Light Theme
# set-option -g status-style fg=black,bg=white
# set-option -g status-left-style fg=black,bg=green
# set-option -g status-style fg=black,bg=#feffff
# set-option -g status-left-style fg=green,bg=#feffff
# set-window-option -g window-status-current-style fg=blue
